// Generated by CoffeeScript 1.6.3
(function() {
  exports.hello = function() {
    return "Hello, global keys: " + Object.keys(global);
  };

  exports.add = function(a, b) {
    return a + b;
  };

  exports.test = {
    shouldSucceed: function() {},
    shouldWarn: function() {
      return "My Warning";
    },
    add: function() {
      if (exports.add(1, 2) !== 3) {
        throw "Things didn't add up";
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
